name: UBC Science Shared Config
type: module
description: This module adds general shared config for the Science suite of sites.
package: UBC Web Services
dependencies:
  - ubc_general_shared_config:ubc_general_shared_config
  - ubc_media_entities:ubc_media_entities
  - ubc_paragraph_entities:ubc_paragraph_entities
core_version_requirement: ^10
